# This is a basic workflow to help you get started with Actions

name: exercio_1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro passo
        run: date
  job2:
    name: Segundo Job
    runs-on: windows-latest
    steps:
      - name: Passo 2
        run: date
        
  job3:
    name: Terceiro Job
    runs-on: macos-latest
    steps:
      - name: Terceiro Passo
        run: date
  
  job4:
    name: Ultimo Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Ultimo Passo
        run: date
        
        

